import "@uploadthing/react/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "sonner";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Story Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gradient-to-br min-h-screen  from-white to-pink-200  text-pink-800`}
      >
        <div className="max-w-[80vw] mx-auto">
          <Navbar />
          {children}
        </div>
        <Toaster richColors />
        <Footer />
      </body>
    </html>
  );
}
